# Generated by Django 4.1.2 on 2023-12-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
    ]
